module.exports = {
    name: 'uraź',
    category: `fun`,
    description: 'Bot cię pociśnie jak nikt nigdy wcześniej. Tylko dla ludzi o mocnych nerwach!',
    permissions: [],
    usage: `<prefix> uraź`,
    aliases: [`obraź`, `wyzwij`, `zwyzywaj`],
    execute(message, args, Discord, client, prefix, colors, command){
        let response = [
            `Zabij się🙃`,
            `Pamiętaj, że większość naszej populacji to debile, więc jest spora szansa, że należysz do tego zrypanego grona 😉`,
            `Jeśli nie masz co robić, to w sumie Twój problem i mam to gdzieś 😀`,
            `Jesteś cepem nad cepy 🤗`,
            `Nikt Cię tu nie chce 😄`,
            `Twój tata na pewno wróci bez mleka i nie będziesz miał co chlać 😂`,
            `Nohybaty 😝`,
            `Co? Gdzie powiesić ten sznurek? Na żyrandolu? Ale po co Ci krzesło?`,
            `Masz problemy psychiczne? Tak? To źle trafiłeś! 😊`,
            `Wiesz, że Twój drugi tatuś też nie wróci z mlekiem? 😆`,
            `Serio? Uważasz bota na Discordzie za przyjaciela? Ja na twoim miejscu już dawno poszedłbym się leczyć...`,
            `Żałosne.`,
            `Ale z Ciebie bahor 😇`,
            `Święty Mikołaj nie istnieje 😎`,
            `Nikt Cię tu nie chce. Nawet boty. Gadałem z nimi 😜`,
            `XDDDDD beka dzieciaczku`,
            `A ssij`,
            `8ball to tylko zabawka, zresztą kostka też...`,
            `Święty Mikołaj istnieje <:zabtroll:847522526615961661>`,
            `Śmieszny żart to Twoja egzystencja 😁`,
            `Administracja z chęcią Cię wydali 😋`,
            `Jesteś kupą <:legocool:755872555214045355>`,
            `Ojjj byniuuuu… Ssij Pryncypały i spadaj mi z oczu 🤢`,
            `Jesteś taki żałosny, że nawet nie chce mi się Ciebie obrażać 😑`,
            `Wszytskie odpowiedzi na ${prefix}pociesz to kłamstwa <:384871347756728321:847522526086168587>`,
            `Twoja mama to nauczycielka niemieckiego :flag_de:`,
            `U MAMA GAY `,
            `doin ur mom <:zabol_swag:847522526493016074>`,
            `Zaraz Cię kfacznę na cock and ball torture`,
            `Jesteś kjepski`,
            `Nie jesteś gyt`,
            `Gdybyś był/a samochodem, był/a/byś MULTIPLĄ`,
            `Bruh ty`,
            `Jesteś jak masło (masło jest słabe)`,
            `U succ`,
            `Help mi step bro mam lowa`,
            `Vanish (zniknij)`,
            `Kup se lepsze mikro pajacu`,
            `Kup se klej`,
            `Nie dostaniesz nawet złamanego bobuxa <:CrookedSmile:847522526229823518>`,
            `Lubię rozpuszczalnik, chcesz trochę?`,
            `kuxxo nie masz talentu, nie imponujesz mi, widziałem lepsze, wypxxxxxxxx idź się zaxxxxx`,
            `Lecisz na hajs `,
            `Ez z toboł xddddd`,
            `Beka z cb typie xddddd`,
            `Zachowaj elegancki dystans <:384871347756728321:847522526086168587>`,
            `We bo gerberek ci wystygnie`,
            `U are gone`
        ];

        message.channel.send(response[Math.floor( Math.random() * response.length )].toString());
    }
}